import { Complaint, Notice, AuditLogItem, Priority, Status } from './types';

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'HST-1048',
    title: 'Severe Water Leakage in Bathroom Pipe',
    category: 'Plumbing',
    description: 'Main pipe connector under sink cracked causing water overflow in Room 302 bathroom. High risk of water damage to electronics.',
    hostelBlock: 'Block A (Men)',
    roomNumber: 'A-302',
    studentName: 'Rohan Sharma',
    studentId: '2023CSB1042',
    studentPhone: '+91 98765-43210',
    status: 'In Progress',
    priority: 'HIGH',
    assignedStaff: 'Ramesh Kumar (Plumber)',
    wardenInCharge: 'Dr. V. K. Gupta',
    createdAt: '2026-10-04T08:30:00Z',
    updatedAt: '2026-10-04T11:15:00Z',
    slaDueDate: '2026-10-04T16:30:00Z',
    slaStatus: 'ON_TRACK',
    resolutionNotes: 'Technician assigned. Replacement pipe acquired from central store.',
  },
  {
    id: 'HST-1049',
    title: 'Wi-Fi Access Point Offline on 4th Floor',
    category: 'Internet/Wi-Fi',
    description: 'Router AP-B4 in Block B east wing lost power/connection. Entire corridor unable to connect to campus network.',
    hostelBlock: 'Block B (Men)',
    roomNumber: '4th Floor Corridor',
    studentName: 'Ananya Verma',
    studentId: '2023ECE1019',
    studentPhone: '+91 98123-45678',
    status: 'Escalated',
    priority: 'HIGH',
    assignedStaff: 'IT Helpdesk - Subodh',
    wardenInCharge: 'Prof. S. R. Naidu',
    createdAt: '2026-10-03T19:45:00Z',
    updatedAt: '2026-10-04T09:00:00Z',
    slaDueDate: '2026-10-04T07:45:00Z',
    slaStatus: 'BREACHED',
    resolutionNotes: 'Escalated to Chief Network Administrator. Fiber optic patch cord replacement needed.',
  },
  {
    id: 'HST-1050',
    title: 'Ceiling Fan Making Loud Grinding Noise',
    category: 'Electrical',
    description: 'Bearing in ceiling fan worn out. Shakes violently at speed 3 and above. Dangerous.',
    hostelBlock: 'Girls Hostel 2',
    roomNumber: 'GH2-114',
    studentName: 'Priya Sundaram',
    studentId: '2022ME1088',
    studentPhone: '+91 97654-32109',
    status: 'Submitted',
    priority: 'MEDIUM',
    assignedStaff: 'Unassigned',
    wardenInCharge: 'Dr. Meenakshi Roy',
    createdAt: '2026-10-04T13:10:00Z',
    updatedAt: '2026-10-04T13:10:00Z',
    slaDueDate: '2026-10-05T13:10:00Z',
    slaStatus: 'ON_TRACK',
  },
  {
    id: 'HST-1051',
    title: 'Study Chair Broken Backrest',
    category: 'Carpentry',
    description: 'Wooden joints split apart on standard desk chair.',
    hostelBlock: 'Block C (Men)',
    roomNumber: 'C-205',
    studentName: 'Amit Patel',
    studentId: '2024EE1005',
    studentPhone: '+91 99887-76655',
    status: 'Resolved',
    priority: 'LOW',
    assignedStaff: 'Suresh Carpenter',
    wardenInCharge: 'Dr. V. K. Gupta',
    createdAt: '2026-10-02T10:00:00Z',
    updatedAt: '2026-10-03T14:20:00Z',
    slaDueDate: '2026-10-05T10:00:00Z',
    slaStatus: 'ON_TRACK',
    resolutionNotes: 'Replaced broken chair with new ergonomic wooden study chair from inventory.',
    feedbackRating: 5,
    feedbackComment: 'Very prompt response! Thanks Suresh uncle.',
  },
  {
    id: 'HST-1052',
    title: 'Corridor Light Switch Sparking (EMERGENCY)',
    category: 'Electrical',
    description: 'Electrical box near Room 108 sparking when turned on. Visible scorch marks.',
    hostelBlock: 'Block A (Men)',
    roomNumber: 'A-108 Ground Floor',
    studentName: 'Vikramaditya S.',
    studentId: '2023CSB1102',
    studentPhone: '+91 98989-89898',
    status: 'In Progress',
    priority: 'EMERGENCY',
    assignedStaff: 'Master Electrician - Rajesh',
    wardenInCharge: 'Dr. V. K. Gupta',
    createdAt: '2026-10-04T14:00:00Z',
    updatedAt: '2026-10-04T14:15:00Z',
    slaDueDate: '2026-10-04T16:00:00Z',
    slaStatus: 'WARNING',
    resolutionNotes: 'Power isolated on Ground Floor East Wing circuit breaker.',
  },
  {
    id: 'HST-1053',
    title: 'Mess Food Quality - Undercooked Rice in Lunch',
    category: 'Mess/Food',
    description: 'Multiple students in Block A/B reported raw rice served during lunch on Oct 4th.',
    hostelBlock: 'Central Mess Hall 1',
    roomNumber: 'Dining Area A',
    studentName: 'Student Council Mess Committee',
    studentId: 'COUNCIL-04',
    studentPhone: '+91 91111-22222',
    status: 'More Info Needed',
    priority: 'HIGH',
    assignedStaff: 'Mess Supervisor - Gopal',
    wardenInCharge: 'Dr. Meenakshi Roy',
    createdAt: '2026-10-04T12:45:00Z',
    updatedAt: '2026-10-04T13:30:00Z',
    slaDueDate: '2026-10-04T18:45:00Z',
    slaStatus: 'ON_TRACK',
    resolutionNotes: 'Requested sample batch log from contractor.',
  }
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'NOT-101',
    title: 'Scheduled Maintenance: Block A & B Water Tank Cleaning',
    content: 'Water supply will be suspended between 9:00 AM to 1:00 PM on Sunday, Oct 6 for bi-annual tank chlorination and inspection.',
    author: 'Chief Hostel Warden Office',
    date: '2026-10-04',
    isImportant: true,
    category: 'Maintenance',
  },
  {
    id: 'NOT-102',
    title: 'Mess Menu Revision Meeting with Student Representatives',
    content: 'All hostel committee representatives are requested to attend the monthly mess menu review in Conference Hall 2 at 5:00 PM.',
    author: 'Hostel Mess Committee',
    date: '2026-10-03',
    isImportant: false,
    category: 'Mess',
  },
  {
    id: 'NOT-103',
    title: 'Strict Warning: High Power Heating Rods & Appliances Prohibited',
    content: 'Random inspection teams will check rooms for unapproved heavy wattage appliances. Violations attract flat penalty of ₹2,000.',
    author: 'Disciplinary Committee',
    date: '2026-10-01',
    isImportant: true,
    category: 'Rules & Policy',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'AUD-901',
    timestamp: '2026-10-04 14:15:02',
    ticketId: 'HST-1052',
    actor: 'Dr. V. K. Gupta',
    role: 'Warden',
    action: 'FLAGGED_EMERGENCY',
    details: 'Ticket escalated to Emergency Priority and dispatched Master Electrician Rajesh.'
  },
  {
    id: 'AUD-902',
    timestamp: '2026-10-04 11:15:00',
    ticketId: 'HST-1048',
    actor: 'Ramesh Kumar',
    role: 'Staff',
    action: 'STATUS_UPDATE',
    details: 'Status changed from Routed -> In Progress. Added resolution note.'
  },
  {
    id: 'AUD-903',
    timestamp: '2026-10-04 09:00:15',
    ticketId: 'HST-1049',
    actor: 'System Automation',
    role: 'System',
    action: 'SLA_BREACH_DETECTED',
    details: 'SLA timer expired for 24h Wi-Fi ticket. Auto-escalated to Chief Admin.'
  },
  {
    id: 'AUD-904',
    timestamp: '2026-10-04 08:30:00',
    ticketId: 'HST-1048',
    actor: 'Rohan Sharma',
    role: 'Student',
    action: 'TICKET_CREATED',
    details: 'New complaint created with priority HIGH.'
  }
];
